# https://aka.ms/yaml
name: $(GitVersion_InformationalVersion)

variables:
  ArtifactName: Modules

resources:
  repositories:
  - repository: templates
    endpoint: PoshCode
    type: github
    name: PoshCode/Azure-Pipelines
    ref: refs/tags/3.2.2

stages:
- stage: Build
  jobs:
  - template: GitVersion-job.yml@templates
  - template: Build-Module-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

- stage: Test
  dependsOn: Build
  jobs:
  - template: ScriptAnalyzer-job.yml@templates
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)

  - template: Pester-job.yml@templates
    parameters:
      dependsOn: []
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests'
      strategy:
        matrix:
          # Linux:
          #   vmImage: 'ubuntu-16.04'
          # MacOS:
          #   vmImage: 'macOS-10.14'
          Windows:
            vmImage: 'windows-2019'
      pool:
        vmImage: $(vmImage)

- stage: Deployment
  dependsOn: Test
  jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      #pool:
      #  vmImage: 'Windows-2019'
      # creates an environment if it doesn't exist
      environment: 'WindowsLab'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: $(ArtifactName)
            - powershell: |
                Get-ChildItem $(Pipeline.Workspace)
                # Invoke-Deployment ... something